version: "2"
volumes:
  mongo-data:
services:
  proxy:
    build: ./provt-proxy
    image: samoyeds/provt-proxy:0.1.1
    ports:
      - "8080:80"
    volumes_from:
      - provt
    links:
      - provt-server
  provt:
    build: ./provt-ui
    image: samoyeds/provt:0.1.1
    entrypoint: /bin/true
    # volumes:
    #   - /app/dist

  provt-server:
    build: ./provt-server
    image: samoyeds/provt-server:0.1.1
    environment:
      - MONGO_URI=mongodb://mongo/provt
    links:
      - mongo

  mongo:
    image: mongo:3.4
    volumes:
      - mongo-data:/data/db
